spring:
  datasource:
    url: jdbc:mysql://118.24.26.31:3306/flyway?useSSL=false
    username: zhouyn
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 3
    consumer:
      group-id: user-data
      auto-offset-reset: latest
      enable-auto-commit: false
      auto-commit-interval: 100
      max-poll-records: 100
    producer:
      retries: 3
      batch-size: 16384
kafka:
  topics:
    user-data: USER_DATA
